//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog_Comment
    {
        public int BC_CommentId { get; set; }
        public Nullable<int> BC_ArticleID { get; set; }
        public Nullable<int> BC_BlogID { get; set; }
        public Nullable<int> BC_UserID { get; set; }
        public Nullable<int> BC_ForUserID { get; set; }
        public Nullable<int> BC_Comment_ParentId { get; set; }
        public Nullable<System.DateTime> BC_Comment_Time { get; set; }
        public string BC_Comment { get; set; }
    }
}
